"""empty message

Revision ID: 7587e260d5bb
Revises: 
Create Date: 2024-09-16 08:49:03.180484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7587e260d5bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_compra_inicial', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acao', schema=None) as batch_op:
        batch_op.drop_column('data_compra_inicial')

    # ### end Alembic commands ###
